logo: '<img src=/Momentum/assets/img/himalayan.jpg>' # add logo name
logo-img: momentum_logo_clear_older.png
logo-img2: momentum_logo_clear.png
title: Momentum - Make Your Move
description: > # this means to ignore newlines until "baseurl:"
  An alternative social contract for men prioritizing transparency over self-promotion.
permalink: ':title/'
baseurl: "/Momentum" # the sub-path of your site, e.g. /blog
url: "http://kimardenmiller.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
poster: momentum_gm.jpg # add banner video. Add your video file to the folder video
video_mp4: momentum_gm.mp4 # add banner video. Add your video file to the folder video
video_ogv: momentum_gm.ogv # add banner video. Add your video file to the folder video
video_webm: momentum_gm.webm # add banner video. Add your video file to the folder video
video_playback_rate: .7

# banner title
banner-title: Momentum
# banner description
banner-desc: An alternative social contract between men that places transparency over self-promotion.
# banner call to action
banner-call-to-action: Meet Us

# Author settings
author-pic: momentum_logo_darker.png # gif portable logo
author-name: Momentum
about-author: Momentum is a local, not-for-profit men’s community supporting men and men’s teams.
about-image: bramhall_circle.jpg
email: info@gomomentum.org # contact email  TODO test live and alert Moe it's coming
website: http://gomomentum.org/ # our main website
contact: /contact/
phone:  # phone number unused as of May 16, 2018

# Social link
meet_up_url:    https://www.meetup.com/GoMomentum/
facebook_url:   https://www.facebook.com/nationofmen/
discourse_url:  http://discourse.gomomentum.org/
google_url:    # add url link
pinterest_url: # add url link
dribbble_url:  # add url link

# Disqus
discus_identifier: gomomentum # add your discus identifier

# Newsletter  TODO Ryan getting the mailchimp plan, but we want Discourse here in the end.
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker TODO set up
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
#exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", ".idea/workspace.xml"]

sass:
    sass_dir: assets/css/sass